CREATE TABLE [Courses] (
    [Course Name]		VARCHAR(512),
    [Subject Area]		VARCHAR(512),
    [Semester]			INT,
    [Required/Elective]	VARCHAR(512)
);

INSERT INTO [Courses] (
	[Course Name], [Subject Area], [Semester], [Required/Elective]
) VALUES
	('Calculus I', 'Computer Science', '1', 'Required'),
	('Linear Algebra', 'Computer Science', '1', 'Required'),
	('Digital Design', 'Hardware', '1', 'Required'),
	('Programming I', 'Software', '1', 'Required'),
	('Foreign language and Technical Terminology', 'Other', '1', 'Required'),
	('Physics I', 'Energy', '1', 'Required'),
	('Calculus II', 'Computer Science', '2', 'Required'),
	('Discrete Mathematics', 'Computer Science', '2', 'Required'),
	('Programming II', 'Software', '2', 'Required'),
	('Methodology of Writing and Presenting Technical Texts', 'Other', '2', 'Required'),
	('Engineering Drawing', 'Energy', '2', 'Required'),
	('Physics II', 'Energy', '2', 'Required'),
	('Circuit Analysis', 'Hardware', '3', 'Required'),
	('Computer Organization & Design', 'Hardware', '3', 'Required'),
	('Probability & Statistics', 'Networking', '3', 'Required'),
	('Electrical Measurements', 'Energy', '3', 'Required'),
	('Data Structures', 'Computer Science', '3', 'Required'),
	('Numerical Analysis', 'Computer Science', '4', 'Required'),
	('Signals and Systems', 'Networking', '4', 'Required'),
	('Algorithms', 'Computer Science', '4', 'Required'),
	('Introduction to Electronics', 'Hardware', '4', 'Required'),
	('Differential Equations', 'Computer Science', '4', 'Required'),
	('Digital Systms Lab', 'Hardware', '5', 'Elective'),
	('Computer Networks I', 'Networking', '5', 'Required'),
	('Concurrent Programming', 'Software', '5', 'Elective'),
	('Compilers', 'Software', '5', 'Elective'),
	('Database Systems I', 'Software', '5', 'Required'),
	('Circuit Analysis II', 'Hardware', '5', 'Elective'),
	('Artificial Intelligence', 'Computer Science', '5', 'Elective'),
	('Automatic Control Systems', 'Energy', '5', 'Required'),
	('Electric Power Generation Systems', 'Energy', '5', 'Elective'),
	('Education Technologies', 'Computer Science', '5', 'Elective'),
	('Linear Programming', 'Computer Science', '5', 'Elective'),
	('Electrical Machines', 'Energy', '5', 'Elective'),
	('Digital Signal Processing', 'Networking', '5', 'Elective'),
	('Digital Systems VLSI', 'Hardware', '5', 'Elective'),
	('Measurement Systems', 'Energy', '6', 'Elective'),
	('Thermodynamics', 'Energy', '6', 'Elective'),
	('Telecommunication Systems', 'Networking', '6', 'Required'),
	('Embedded Systems', 'Hardware', '6', 'Elective'),
	('SoC CAD Lab', 'Hardware', '6', 'Elective'),
	('Advanced Electronics', 'Hardware', '6', 'Elective'),
	('Parallel Computer Architecture', 'Hardware', '6', 'Elective'),
	('Power Systems I', 'Energy', '6', 'Required'),
	('Image Processing', 'Networking', '6', 'Elective'),
	('System Modeling and Performance', 'Networking', '6', 'Elective'),
	('Pattern Recognition', 'Networking', '6', 'Elective'),
	('Electromagnetic Fields I', 'Hardware', '6', 'Required'),
	('Alternative Energy Sources', 'Energy', '6', 'Elective'),
	('Electric Drive Systems', 'Energy', '6', 'Elective'),
	('Operating Systems', 'Software', '6', 'Elective'),
	('Electrotechnical Materials', 'Energy', '6', 'Elective'),
	('Introduction to the Theory of Computation', 'Computer Science', '6', 'Elective'),
	('Object Oriented Programming', 'Software', '6', 'Elective'),
	('Information Retrieval', 'Software', '6', 'Elective'),
	('Distributed Systems', 'Software', '6', 'Elective'),
	('Power Electronics', 'Energy', '6', 'Elective'),
	('Introduction to Entrepreneurship', 'Other', '7', 'Elective'),
	('Special Topics / Projects', 'Other', '7', 'Elective'),
	('Advanced Telecommunication Systems', 'Networking', '7', 'Elective'),
	('Hardware Security', 'Hardware', '7', 'Elective'),
	('Speech and Audio Processing', 'Networking', '7', 'Elective'),
	('Inter-network Protocol Design', 'Networking', '7', 'Elective'),
	('Neuro-Fuzzy Computing', 'Computer Science', '7', 'Elective'),
	('Parallel and Distributed Computing', 'Computer Science', '7', 'Elective'),
	('Computer Graphics', 'Computer Science', '7', 'Elective'),
	('Computer Algebra I', 'Computer Science', '7', 'Elective'),
	('Introduction to Nanoelectronics', 'Hardware', '7', 'Elective'),
	('Introduction to Computer Vision', 'Networking', '7', 'Elective'),
	('Information and Coding Theory', 'Networking', '7', 'Elective'),
	('Testing and Verification of Digital Circuits', 'Hardware', '7', 'Elective'),
	('Power Systems II', 'Energy', '7', 'Elective'),
	('Electromagnetic Fields II', 'Hardware', '7', 'Elective'),
	('High Performance Computing Systems', 'Software', '7', 'Elective'),
	('WWW Technologies', 'Software', '7', 'Elective'),
	('High Voltage Engineering', 'Energy', '7', 'Elective'),
	('Electrical Installations', 'Energy', '7', 'Elective'),
	('Logic and Functional Programming', 'Software', '7', 'Elective'),
	('Smart Grids', 'Energy', '7', 'Elective'),
	('CAD Algorithms', 'Hardware', '7', 'Elective'),
	('Special Topics / Projects', 'Other', '8', 'Elective'),
	('Technology Economics', 'Other', '8', 'Elective'),
	('Product and Service Design', 'Other', '8', 'Elective'),
	('Advanced Energy Conversion Systems', 'Energy', '8', 'Elective'),
	('Wireless Communications', 'Networking', '8', 'Elective'),
	('Computer networks II', 'Networking', '8', 'Elective'),
	('Introduction to Energy Economics', 'Energy', '8', 'Elective'),
	('Industrial Automation and Control', 'Energy', '8', 'Elective'),
	('Advanced Automatic Control Systems', 'Networking', '8', 'Elective'),
	('Networks and Information Systems Security', 'Networking', '8', 'Elective'),
	('Wireless Mobile Communications', 'Networking', '8', 'Elective'),
	('Special Topics of Electrical Installations', 'Energy', '8', 'Elective'),
	('Greek Economy', 'Other', '8', 'Elective'),
	('Electroacoustics', 'Energy', '8', 'Elective'),
	('Modern Electrical Transmission and Distribution Systems', 'Energy', '8', 'Elective'),
	('Control and Stability of Power Systems', 'Energy', '8', 'Elective'),
	('Audio and Video Conding', 'Networking', '8', 'Elective'),
	('Radhard Circuit Design', 'Hardware', '8', 'Elective'),
	('Applied Stochastic Processes', 'Networking', '8', 'Elective'),
	('Design of Analog/Mixed Signal and RF Circuits', 'Hardware', '8', 'Elective'),
	('Network Optimization', 'Networking', '8', 'Elective'),
	('Software Engineering', 'Software', '8', 'Elective'),
	('Advanced Data Management', 'Software', '8', 'Elective'),
	('Complex Networks', 'Software', '8', 'Elective'),
	('Advanced Compiler Topics', 'Software', '8', 'Elective'),
	('Multiagent Systems', 'Software', '8', 'Elective'),
	('Physical CAD Algorithms', 'Hardware', '8', 'Elective'),
	('Data Mining', 'Software', '8', 'Elective'),
	('Logical Foundations for Intelligent Agents', 'Computer Science', '8', 'Elective'),
	('Introduction to Robotics', 'Computer Science', '8', 'Elective'),
	('Machine Learning for Data Science and Analytics', 'Computer Science', '8', 'Elective'),
	('Special Topics in Applied Mathematics', 'Computer Science', '8', 'Elective'),
	('Integer Programming and Combinatorial Optimization', 'Computer Science', '8', 'Elective'),
	('Game Architecture and Development', 'Computer Science', '8', 'Elective'),
	('Computer Algebra II', 'Computer Science', '8', 'Elective'),
	('Blockchain Technologies and Decentralized Applications', 'Software', '8', 'Elective'),
	('Computational Modeling of Materials for Microelectronic Applications', 'Hardware', '8', 'Elective'),
	('Advanced Topics in System Software', 'Software', '8', 'Elective'),
	('Industrial IoT (Internet of Things) and Applications', 'Hardware', '8', 'Elective'),
	('Microprocessor Design', 'Hardware', '8', 'Elective'),
	('Low Power Design', 'Hardware', '8', 'Elective'),
	('Asynchronous Circuit Design', 'Hardware', '8', 'Elective'),
	('Sensor Design', 'Hardware', '9', 'Elective'),
	('Special Subjects', 'Computer Science', '9', 'Elective'),
	('Energy and the Environment', 'Energy', '9', 'Elective'),
	('Computational Methods in Power Systems', 'Energy', '9', 'Elective'),
	('Protection of Power Systems', 'Energy', '9', 'Elective'),
	('Problem Solving Environments and Applications in Data Science', 'Computer Science', '9', 'Elective'),
	('Analog Circuits Lab', 'Hardware', '9', 'Elective'),
	('Optoelectronics', 'Hardware', '9', 'Elective'),
	('Manufacturing of Semiconductor Devices', 'Hardware', '9', 'Elective'),
	('Advanced Topics in CAD Algorithms', 'Hardware', '9', 'Elective'),
	('Advanced Computer Architecture', 'Hardware', '9', 'Elective'),
	('Computational Geometry', 'Computer Science', '9', 'Elective'),
	('Advanced Telecommunication Systems', 'Networking', '9', 'Elective'),
	('Statistics', 'Networking', '9', 'Elective'),
	('Antennas', 'Networking', '9', 'Elective'),
	('Microwaves', 'Networking', '9', 'Elective'),
	('Advanced Topics in Computer Networks', 'Networking', '9', 'Elective'),
	('Advanced Topics in Speech and Language Processing', 'Networking', '9', 'Elective'),
	('Mobile & Pervasive Computing', 'Software', '9', 'Elective'),
	('Human - Machine Interaction', 'Software', '9', 'Elective'),
	('Database Management Systems II', 'Software', '9', 'Elective'),
	('Design Thinking', 'Software', '9', 'Elective'),
	('Advanced Software Engineering', 'Software', '9', 'Elective'),
	('Circuit Simulation Algorithms', 'Hardware', '9', 'Elective'),
	('Wireless Sensor Network Programming', 'Software', '9', 'Elective'),
	('Advanced Distributed Computing', 'Software', '9', 'Elective'),
	('Big Data Mining', 'Software', '9', 'Elective'),
	('Computational Methods for Electromagnetics', 'Software', '9', 'Elective'),
	('Technical and Academic Writing', 'Other', '9', 'Elective'),
	('Legal Subjects in Informatics & Telecommunications', 'Other', '9', 'Elective');